## Numpy:

* Numpy --- Numerical Python
* Numpy is a library in python which is used to built different dimensuonal arrays

In [44]:
import numpy as np
a=[1,2,3,4,5]
data=np.array(a)
print(data)

[1 2 3 4 5]


In [6]:
type(a)

list

In [8]:
b=[0,1,2,3,4]
data1=np.array(b)
print(data1)

[0 1 2 3 4]


In [9]:
type(data1)

numpy.ndarray

In [18]:
data2=np.array([[1,2,3,4],[5,6,7,8]])               ### 2_Dimensional array

In [19]:
data2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
data3=np.array([[1,2,3,4],[5,6,7,8],[0,1,9,3]])     ### 3_Dimensional array

In [21]:
data3

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 1, 9, 3]])

In [20]:
data2.shape                                      ### Length of the array

(2, 4)

In [22]:
data3.shape

(3, 4)

In [25]:
### arranging data in an array:

data=np.arange(0,101)
print(data)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [26]:
data.shape

(101,)

In [27]:
data=np.arange(1,101)

In [28]:
data

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [29]:
data1=data.reshape(10,10)

In [30]:
data1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [31]:
## to print particular range of elements

data1=np.linspace(0,8,10)

In [32]:
data1

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [33]:
data1=np.linspace(0,8,20)
data1

array([0.        , 0.42105263, 0.84210526, 1.26315789, 1.68421053,
       2.10526316, 2.52631579, 2.94736842, 3.36842105, 3.78947368,
       4.21052632, 4.63157895, 5.05263158, 5.47368421, 5.89473684,
       6.31578947, 6.73684211, 7.15789474, 7.57894737, 8.        ])

In [34]:
### to print elements randomly in an array

data=np.random.randint(0,20,size=(2,4))
data

array([[12, 15, 17, 18],
       [18, 14,  7,  2]])

In [35]:
### To print only ones in the array 
data=np.ones((4,3))
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
data=np.ones((4,3),int)
data

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [38]:
data=np.zeros((4,3),int)
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
data=np.twos((4,3),int)
data

AttributeError: module 'numpy' has no attribute 'twos'

In [47]:
n=np.ones((4,3),int)
n
np.vstack([n,n*10])

array([[ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [48]:
n=np.ones((4,3),int)
n
np.hstack([n,n*10])

array([[ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10]])

## Array Operators:

In [51]:
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
n1+n2

array([ 6,  8, 10, 12])

In [53]:
n2-n1

array([4, 4, 4, 4])

In [54]:
n1*n2

array([ 5, 12, 21, 32])

In [55]:
n2/n1

array([5.        , 3.        , 2.33333333, 2.        ])

In [56]:
n1,n2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [57]:
n1**n2

array([    1,    64,  2187, 65536], dtype=int32)

In [58]:
n2**n1

array([   5,   36,  343, 4096], dtype=int32)

In [59]:
n1%n2

array([1, 2, 3, 4], dtype=int32)

In [60]:
n1**3

array([ 1,  8, 27, 64], dtype=int32)

In [61]:
n1&n2

array([1, 2, 3, 0], dtype=int32)

In [62]:
n1| n2

array([ 5,  6,  7, 12], dtype=int32)

In [63]:
n1.all()

True

In [64]:
n1.dot(n2)

70

In [65]:
data1

array([0.        , 0.42105263, 0.84210526, 1.26315789, 1.68421053,
       2.10526316, 2.52631579, 2.94736842, 3.36842105, 3.78947368,
       4.21052632, 4.63157895, 5.05263158, 5.47368421, 5.89473684,
       6.31578947, 6.73684211, 7.15789474, 7.57894737, 8.        ])

In [66]:
data2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
data2.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [69]:
print(data2.transpose())

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [70]:
data1.max()

8.0

In [72]:
data1.min()

0.0

In [73]:
data2.max()

8

In [76]:
data2.min()

1

In [77]:
data2.sum()

36

In [78]:
data2.mean()

4.5

In [79]:
np.sqrt(data1)

array([0.        , 0.64888568, 0.91766294, 1.12390297, 1.29777137,
       1.4509525 , 1.58943883, 1.71679015, 1.83532587, 1.94665705,
       2.0519567 , 2.15211035, 2.24780595, 2.33959061, 2.42790791,
       2.51312345, 2.59554274, 2.67542422, 2.75298881, 2.82842712])