### 1.Write a pandas program to change the order of a given series.

In [1]:
import pandas as pd
import numpy as np

In [75]:
a=pd.Series([1,2,3,4],['a','b','c','d'])
a

a    1
b    2
c    3
d    4
dtype: int64

In [77]:
a.reindex(['b','c','d','a'])

b    2
c    3
d    4
a    1
dtype: int64

#### 3.write a pandas program to convert a panda module series to python list and its type

In [17]:
a=pd.Series([1,2,3,4])

In [18]:
a

0    1
1    2
2    3
3    4
dtype: int64

In [19]:
a=list(a)

In [20]:
a

[1, 2, 3, 4]

In [21]:
type(a)

list

#### 4.Write a pandas program to select the rows where the score is missing i.e. is NaN

In [22]:
exam_data={'name':['Sachin','Ganguly','Kohli',"johnson",'Taylor','Waugh','Yuvraj','Kambli','Srinath','Munaf'],
           'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
          'attempts':[1,3,2,3,2,3,1,1,2,1],
          'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
labels=['a','b','c','d','e','f','g','h','i','j']

In [23]:
pd.DataFrame(exam_data)

name  score  attempts qualify
0   Sachin   12.5         1     yes
1  Ganguly    9.0         3      no
2    Kohli   16.5         2     yes
3  johnson    NaN         3      no
4   Taylor    9.0         2      no
5    Waugh   20.0         3     yes
6   Yuvraj   14.5         1     yes
7   Kambli    NaN         1      no
8  Srinath    8.0         2      no
9    Munaf   19.0         1     yes

In [24]:
pd.DataFrame(labels)

0
0  a
1  b
2  c
3  d
4  e
5  f
6  g
7  h
8  i
9  j

#### 2.Write a pandas program to add,subtract,mutiply and division

In [26]:
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,9])

In [28]:
c=a+b
c

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [29]:
c=a-b
c

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [30]:
c=a*b
c

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [31]:
c=a/b
c

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

#### 5.Write a pandas program to create todays date

In [41]:
from datetime import date

In [42]:
date?

In [80]:
date.today()

datetime.date(2019, 12, 28)

#### 7.Write a numpy program to create a 3x3 matrix with values ranging from 2 to 10

In [47]:
a=np.arange(2,11)

In [48]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 8.Illustrate the difference between ravel and flatten by taking considering mutidimensional array

In [53]:
c=([[1,2,3,4],[3,4,5,6],[4,5,6,7]])
c

[[1, 2, 3, 4], [3, 4, 5, 6], [4, 5, 6, 7]]

In [55]:
np.ravel?

In [56]:
b=np.ravel(c)

In [57]:
b

array([1, 2, 3, 4, 3, 4, 5, 6, 4, 5, 6, 7])

In [58]:
c

[[1, 2, 3, 4], [3, 4, 5, 6], [4, 5, 6, 7]]

In [63]:
np.ravel?

In [66]:
b=np.flatend(c)

AttributeError: module 'numpy' has no attribute 'flatend'

### question9

In [67]:
b=([1,2,3,4],[3,4,5,6],[6,4,7,8])
b

([1, 2, 3, 4], [3, 4, 5, 6], [6, 4, 7, 8])

In [68]:
np.min(b)

1

In [69]:
np.max(b)

8

In [70]:
np.cumsum(b)

array([ 1,  3,  6, 10, 13, 17, 22, 28, 34, 38, 45, 53], dtype=int32)

In [71]:
np.cumprod(b)

array([       1,        2,        6,       24,       72,      288,
           1440,     8640,    51840,   207360,  1451520, 11612160],
      dtype=int32)

In [73]:
np.std(b)

1.9773017529507788